# Executables
pnnl_path = "C:\\Program Files\\PNNL-Preprocessor\\PNNL-PreProcessor.exe"
start_mh_rf_path = "C:\\Agilent\\RapidFire Communicator\\RFMassHunter_NET\\bin\\Start_MassHunter_S.bat"
rapid_fire_data_dir = "D:\\Projects\\Default\\Data\\RapidFire"
mh_splitter_exe = "D:\\gkreder\\RapidFire_bin\\MHFileSplitter.exe"
msconvert_exe = "C:\\Users\\admin\\AppData\\Local\\Apps\\ProteoWizard 3.0.22173.4a1045d 64-bit\\msconvert.exe"
skyline_exe = "C:\\Users\\admin\\Desktop\\SkylineCmd.exe.lnk"